### ISSUE TITLE
mdmctl SIGSEGV when sending DEP commands

### ISSUE THREAD

**Issue by chrisyeo** [micromdm/micromdm#465]
### What version of `micromdm` are you using?
micromdm 1.3.1 (Linux) : mdmctl 1.3.1 (macOS)
### What `micromdm` command did you run?
mdmctl get dep-account (or any command that speaks to DEP)
### What did you expect to see?
Happy, fluffy clouds
### What did you see instead?

**mdmctl:**
```
OrgName  OrgPhone  OrgEmail  ServerName
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1373bad]

goroutine 1 [running]:
main.(*getCommand).getDEPAccount(0xc420099050, 0xc42009c0b0, 0x0, 0x0, 0x0, 0x0)
	/Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/get_dep_account.go:36 +0x1fd
main.(*getCommand).(main.getDEPAccount)-fm(0xc42009c0b0, 0x0, 0x0, 0xb, 0x0)
	/Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/get.go:62 +0x48
main.(*getCommand).Run(0xc420099050, 0xc42009c0b0, 0x1, 0x1, 0xc42005be01, 0xc420099050)
	/Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/get.go:82 +0x151
main.(*getCommand).Run-fm(0xc42009c0b0, 0x1, 0x1, 0x3, 0x7e0ee28124fe01af)
	/Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/mdmdctl.go:31 +0x48
main.main()
	/Users/victor/go/src/github.com/micromdm/micromdm/cmd/mdmctl/mdmdctl.go:49 +0x19b
```

**micromdm**
```---BEGIN Response---
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Type: application/json; charset=utf-8

{
  "error": "Error establishing DEP session: 400 Bad Request"
}

---END Response---```

**Comment by chrisyeo** [comment]
Forgot to mention that I get a 400 error code when micromdm starts:
```component=main msg=started
level=info msg="loaded DEP config" cursor=
level=info msg="serving HTTPS using provided certificates" addr=:443
level=info err="Error establishing DEP session: 400 Bad Request" msg="DEP watcher failed"
level=info msg="saved DEP config" cursor=
```

**Comment by chrisyeo** [comment]
It's ASM

**Comment by chrisyeo** [comment]
Took a shower and a couple of weeks off, decided to try this again and had great success. Closing :)

**Comment by chrisyeo** [comment]
Sadly having to reopen this; silver lining - I only get this issue with the linux 1.3.1 build. I got it working earlier on my Mac. That should help (I hope)
