### ISSUE TITLE
Help wanted with mdmcert.download

### ISSUE THREAD

**Issue by carlos-alarcon** [micromdm/micromdm#554]
### What version of `micromdm` are you using?
v1.4.0

### What `micromdm` command did you run?
(Following directions at https://github.com/micromdm/micromdm/wiki/mdmcert.download)
 I requested a csr to mdmcert.download, decrypted it and uploaded the mdmcert.download.push.req
to https://identity.apple.com. It gave us the MDM_McMurtrieConsultingLLC_Certificate.pem (I just renamed it to avoid spaces)

./mdmctl mdmcert upload -cert=$(pwd)/MDM_McMurtrieConsultingLLC_Certificate.pem -private-key=mdm-certificates/mdmcert.download.push.key 

### What did you expect to see?
success or something similar.

### What did you see instead?
upload push certificate and key to server: Put /v1/config/certificate: unsupported protocol scheme ""

**Comment by carlos-alarcon** [comment]
Ok sorry. Seems I missed to setup mdmctl config first (as said in the quickstart guide: https://github.com/micromdm/micromdm/wiki/Quickstart).
### What micromdm command did you run?
`./mdmctl config set   -name production   -api-token XXXXXX   -server-url https://mdm-carlos.iontab-dev.es:4537` 

### What did you expect to see?
Something telling me the production config was set

### What did you see instead?

> panic: assignment to entry in nil map
> goroutine 1 [running]:
> main.saveServerConfig(0xc00003fdf8, 0x7ffd9c4fc343, 0xa, 0x17, 0x0)
> 	/Users/victor/code/micromdm/cmd/mdmctl/config.go:258 +0xc3
> main.setCmd(0xc00000e0c0, 0x6, 0x6, 0x3, 0x0)
> 	/Users/victor/code/micromdm/cmd/mdmctl/config.go:161 +0x2e6
> main.(*configCommand).Run(0xc00000c040, 0xc00000e0b0, 0x7, 0x7, 0x1, 0xc00000c040)
> 	/Users/victor/code/micromdm/cmd/mdmctl/config.go:62 +0xf5
> main.(*configCommand).Run-fm(0xc00000e0b0, 0x7, 0x7, 0x6, 0xffffffffffffffff)
> 	/Users/victor/code/micromdm/cmd/mdmctl/mdmdctl.go:28 +0x48
> main.main()
> 	/Users/victor/code/micromdm/cmd/mdmctl/mdmdctl.go:49 +0x185


### Where I am running the server
Using Linux debian stretch 

### Command use to start the server:

> sudo ./micromdm serve   -server-url=https://mdm-carlos.iontab-dev.es:4537   -api-key XXXXX   -http-addr :4537   -tls-cert $(pwd)/iontab-dev.crt.pem   -tls-key $(pwd)/iontab-dev.key.pem   -tls true


### Output in the server console

> component=main msg=started
> ts="2018/12/18 17:33:19" msg="push: waiting for push certificate before enabling APNS service provider"
> level=info msg="loaded DEP config" cursor=
> level=info msg="waiting for DEP token to be added before starting sync"
> level=info msg="serving HTTPS using provided certificates" addr=:4537
>

**Comment by carlos-alarcon** [comment]
Using mdmctl from a macos device seems to work (using binary from darwin folder)
Seems that mdmctl binary under linux folder is not ok. Server still working in linux (and is working so far, I had just uploaded the push certificate, exported DEP public key and imported the DEP token)

**Comment by nebevservian** [comment]
I got the same error - I fixed it by removing the ~/.micromdm/servers.json completely on the affected box. Then the config command seems to work without error.

**Comment by AbhishekNuevo** [comment]
I removed the ~/.micromdm/servers.json completely but still getting the error. Put /v1/config/certificate: unsupported protocol scheme ""
@carlos-alarcon How did you resolve it?. I using MAC Os - Mojave. I have tried all the tricks but failed. I have stuck for 2 days.

**Comment by carlos-alarcon** [comment]
Not sure because its been a time since then (and currently we aren't  working on it) but I would say I just removed the file they mention.

**Comment by yiios** [comment]
I have encountered the same problem. The log output is the same. Is there a solution?

**Comment by yiios** [comment]
I executed the following code to solve this problem.
`mdmctl config switch -name production`

**Comment by honeyankit** [comment]
- I am also hitting the same issue as described in the first [comment](https://github.com/micromdm/micromdm/issues/554#issue-392211653) on the issue and need help?

My mdmctl version:
```
bootstrap@maccloud-mdm-server:~/micromdm/build/linux$ ./mdmctl version
mdmctl version v1.9.0-beta-4-gba38781-dirty
```

- Steps executed by me:
1. I requested a csr to mdmcert.download
2. decrypted it and uploaded the mdmcert.download.push.req to https://identity.apple.com.
3. It gave me the `MDM_McMurtrieConsultingLLC_Certificate.cer` instead of `MDM_McMurtrieConsultingLLC_Certificate.pem` as stated by others.
3. Finally I run the `mdmctl mdmcert upload`
./mdmctl mdmcert upload -cert=$(pwd)/MDM_McMurtrieConsultingLLC_Certificate.cer -private-key=mdm-certificates/mdmcert.download.push.key

Error: `upload push certificate and key to server: Put /v1/config/certificate: unsupported protocol scheme ""`

**Comment by honeyankit** [comment]
> * I am also hitting the same issue as described in the first [comment](https://github.com/micromdm/micromdm/issues/554#issue-392211653) on the issue and need help?
> * My mdmctl version:
> 
> ```
> bootstrap@maccloud-mdm-server:~/micromdm/build/linux$ ./mdmctl version
> mdmctl version v1.9.0-beta-4-gba38781-dirty
> ```
> 
> * Environment:
> 
> ```
> bootstrap@maccloud-mdm-server:~/micromdm/build/linux$ cat /etc/lsb-release 
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=20.04
> DISTRIB_CODENAME=focal
> DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
> ```
> 
> * Steps executed by me:
> 
> 1. I requested a csr to mdmcert.download
> 2. decrypted it and uploaded the mdmcert.download.push.req to https://identity.apple.com.
> 3. It gave me the `MDM_McMurtrieConsultingLLC_Certificate.cer` instead of `MDM_McMurtrieConsultingLLC_Certificate.pem` as stated by others.
> 4. Finally I run the `mdmctl mdmcert upload`
>    ./mdmctl mdmcert upload -cert=$(pwd)/MDM_McMurtrieConsultingLLC_Certificate.cer -private-key=mdm-certificates/mdmcert.download.push.key
> 
> Error: `upload push certificate and key to server: Put /v1/config/certificate: unsupported protocol scheme ""`

- I was able to fix the issue. The issue was that config was not created. Once I created the config and then again tired to upload the cert, it succeeded.

Steps to fix:

1. Create the config 
```
./mdmctl config set -name stating -api-token xxyyzz -server-url https://xyz.com
```

2. Uploaded the cert again and it worked. 
```
./mdmctl mdmcert upload -cert=MDM_McMurtrieConsultingLLC_Certificate.cer -private-key=mdm-certificates/mdmcert.download.push.key
```

- If you are running the `micromdm serve`  on the another terminal if you show you below logs stating push service started as it needs push certificate to start.
```
transport=http method=PUT status=200 proto=HTTP/2.0 host=20.120.224.153 user_agent=Go-http-client/2.0 path=/v1/config/certificate
ts="2022/01/21 23:29:44" msg="push: service started"
```
